Repository RedHatQE/widgetastic.patternfly, pull requests merged in 2018-12, with the labels that each got.

#76 [RFR] fix flash messages in hammer
  src/widgetastic_patternfly/__init__.py
Labels: bug, enhancement

#80 Add fa-angle icons to IconConstants
  src/widgetastic_patternfly/utils.py
Labels: enhancement

#79 [1LP][RFR] read method to Dropdown
  src/widgetastic_patternfly/__init__.py
Labels: bug
